=== mju-sysolab/trident/trident-src/fp/hwdesc/hw.dtd
<!ELEMENT hardware (name|chip)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT chip (name|count|size|word_size|area_max_usage|area_min_usage|area|resource|port|address)*>
<!ATTLIST chip type (fpga|ram|rom) "rom">
<!ELEMENT area_max_usage (#PCDATA)>
<!ELEMENT area_min_usage (#PCDATA)>
<!ELEMENT area (#PCDATA)>
<!ELEMENT resource (name|count|size|address|dimension1|dimension2)*>
<!ATTLIST resource type (blockram|multiplier|register) "blockram">
<!ELEMENT count (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT word_size (#PCDATA)>
<!ELEMENT dimension1 (#PCDATA)>
<!ELEMENT dimension2 (#PCDATA)>
<!ELEMENT port (name|count|size|read_latency|write_latency|clock)*>
<!ATTLIST port type (address_read|address_write|address_rw|data_read|data_write|data_rw) "data_read">

=== mju-sysolab/trident/trident-src/fp/hwdesc/default_hw.xml
<!--
 
 LA-CC 05-135 Trident 0.7.1

Copyright Notice
Copyright 2006 (c) the Regents of the University of California.

This Software was produced under a U.S. Government contract
(W-7405-ENG-36) by Los Alamos National Laboratory, which is operated
by the University of California for the U.S. Department of Energy. The
U.S. Government is licensed to use, reproduce, and distribute this
Software. Permission is granted to the public to copy and use this
Software without charge, provided that this Notice and any statement
of authorship are reproduced on all copies. Neither the Government nor
the University makes any warranty, express or implied, or assumes any
liability or responsibility for the user of this Software.


-->


<?xml version='1.0' standalone="no"?>

<!DOCTYPE hardware SYSTEM "hw.dtd">

<hardware>
 <name>default</name>
 <chip type="fpga">
  <name>fpga_default</name>
  <area_max_usage>1.0</area_max_usage>
  <area_min_usage>.2</area_min_usage>
  <area>100000</area>
 </chip>

 <!-- dual ported RAM with one read and one write port --> 
 <chip type="ram">
  <count>10</count>
  <name>mem_0</name>
  <word_size>128</word_size>
  <size>64</size>

  <port type="address_read">
   <count> 1 </count>
  </port>

  <port type="address_write">
   <count> 1 </count>
  </port>

  <port type="data_read">
   <count>1</count>
   <size>128</size>
   <read_latency>4</read_latency>
   <clock>1</clock>
  </port>

  <port type="data_write">
   <count>1</count>
   <size>128</size>
   <write_latency>1</write_latency>
   <clock>1</clock>
  </port>

 </chip>

 <!-- single-ported ram --> 
 <chip type="ram">
  <count>1</count>
  <name>mem_1</name>
  <word_size>128</word_size>
  <size>64</size>

  <port type="address_rw">
   <count> 1 </count>
  </port>
  
  <port type="data_rw">
   <count>1</count>
   <size>128</size>
   <read_latency>4</read_latency>
   <write_latency>1</write_latency>
   <clock>1</clock>
  </port>

 </chip>

 <!-- Read only memory -->
 <chip type="rom">
  <count>1</count>
  <name>mem_2</name>
  <word_size>128</word_size>
  <size>64</size>

  <port type="address_read">
   <count> 1 </count>
  </port>

  <port type="data_read">
   <count>1</count>
   <size>128</size>
   <read_latency>4</read_latency>
   <clock>1</clock>
  </port>
  
 </chip>

 <!-- half dual ported RAM (ie. a write bus and a read bus, but only 1 address bus) -->
 <chip type="ram">
  <count>1</count>
  <name>mem_3</name>
  <word_size>32</word_size>
  <size>256</size>

  <port type="address_rw">
   <count> 1 </count>
  </port>
  
  <port type="data_read">
   <count>1</count>
   <size>32</size>
   <read_latency>4</read_latency>
   <clock>1</clock>
  </port>
  
  <port type="data_write">
   <count>1</count>
   <size>32</size>
   <write_latency>1</write_latency>
   <clock>1</clock>
  </port>

 </chip>

 <!-- read only mem with 2 read ports -->
 <chip type="rom">
  <count>1</count>
  <name>mem_4</name>
  <word_size>256</word_size>
  <size>32</size>

  <port type="address_read">
   <count> 2 </count>
  </port>

  <port type="data_read">
   <count>2</count>
   <size>32</size>
   <read_latency>4</read_latency>
   <clock>1</clock>
  </port>
  
 </chip>

 <!-- just for laughs... write only mem with 2 write ports -->
 <chip type="ram">
  <count>1</count>
  <name>mem_5</name>
  <word_size>16</word_size>
  <size>512</size>

  <port type="address_write">
   <count> 2 </count>
  </port>

  <port type="data_write">
   <count>2</count>
   <size>16</size>
   <write_latency>1</write_latency>
   <clock>1</clock>
  </port>
  
 </chip>

 <!-- boring, old normal memory, with 2 read and 2 write ports -->
 <chip type="ram">
  <count>1</count>
  <name>mem_6</name>
  <word_size>32</word_size>
  <size>256</size>

  <port type="address_read">
   <count> 2 </count>
  </port>

  <port type="data_read">
   <count>2</count>
   <size>32</size>
   <read_latency>4</read_latency>
   <clock>1</clock>
  </port>
  
  <port type="address_write">
   <count> 2 </count>
  </port>

  <port type="data_write">
   <count>2</count>
   <size>32</size>
   <write_latency>1</write_latency>
   <clock>1</clock>
  </port>
  
 </chip>
  
  <!-- boring, old normal (bigger) memory, with 2 read and 2 write ports -->
 <chip type="ram">
  <count>1</count>
  <name>mem_6</name>
  <word_size>32</word_size>
  <size>1280</size>

  <port type="address_read">
   <count> 2 </count>
  </port>

  <port type="data_read">
   <count>2</count>
   <size>32</size>
   <read_latency>4</read_latency>
   <clock>1</clock>
  </port>
  
  <port type="address_write">
   <count> 2 </count>
  </port>

  <port type="data_write">
   <count>2</count>
   <size>32</size>
   <write_latency>1</write_latency>
   <clock>1</clock>
  </port>
  
 </chip>
  
</hardware>

=== mju-sysolab/trident/trident-src/fp/hwdesc/xd1_hw.xml
<!--
 
 LA-CC 05-135 Trident 0.7.1

Copyright Notice
Copyright 2006 (c) the Regents of the University of California.

This Software was produced under a U.S. Government contract
(W-7405-ENG-36) by Los Alamos National Laboratory, which is operated
by the University of California for the U.S. Department of Energy. The
U.S. Government is licensed to use, reproduce, and distribute this
Software. Permission is granted to the public to copy and use this
Software without charge, provided that this Notice and any statement
of authorship are reproduced on all copies. Neither the Government nor
the University makes any warranty, express or implied, or assumes any
liability or responsibility for the user of this Software.


-->


<?xml version='1.0' standalone="no"?>

<!DOCTYPE hardware SYSTEM "hw.dtd">

<hardware>
 <name>xd1</name>  <!-- Cray -->
 <chip type="fpga">
  <count>1</count>
  <name>Xilinx_Virtex-II_Pro_50</name> 
  <area_max_usage>.9</area_max_usage>
  <area_min_usage>.15</area_min_usage>
  <area>33792</area>

  <resource type="register">
    <name>user_registers</name>
    <address>0x4000000</address>
  </resource>

  <resource type="blockram">
   <count>232</count>
   <size>18432</size> <!-- 18 Kb -->
  </resource>
 
  <resource type="multiplier">
    <count>232</count>
    <dimension1>18</dimension1>
    <dimension2>18</dimension2>
  </resource>

 </chip>

 <!-- QDR SRAM --> 
 <chip type="ram">
  <count>4</count>
  <name>qdr_sram</name>
  <word_size>64</word_size> <!-- 8 X 8-bit bytes -->
  <size>524288</size>  <!-- # 64b words --> <!-- supposed to be 524288 -->
  <address>0x0</address>

  <port type="address_read">
   <size>20</size>
   <count> 1 </count>
   <clock>1</clock>
  </port>

  <port type="address_write">
   <size>20</size>
   <count> 1 </count>
   <clock>1</clock>
  </port>

  <port type="data_read">
   <count>1</count>
   <size>64</size>
   <read_latency>8</read_latency>
   <clock>1</clock>
  </port>

  <port type="data_write">
   <count>1</count>
   <size>64</size>
   <write_latency>1</write_latency>
   <clock>1</clock>
  </port>

 </chip>

</hardware>

=== mju-sysolab/trident/trident-src/fp/hwdesc/osiris_hw.xml
<!--
 
 LA-CC 05-135 Trident 0.7.1

Copyright Notice
Copyright 2006 (c) the Regents of the University of California.

This Software was produced under a U.S. Government contract
(W-7405-ENG-36) by Los Alamos National Laboratory, which is operated
by the University of California for the U.S. Department of Energy. The
U.S. Government is licensed to use, reproduce, and distribute this
Software. Permission is granted to the public to copy and use this
Software without charge, provided that this Notice and any statement
of authorship are reproduced on all copies. Neither the Government nor
the University makes any warranty, express or implied, or assumes any
liability or responsibility for the user of this Software.


-->


<?xml version='1.0' standalone="no"?>

<!DOCTYPE hardware SYSTEM "hw.dtd">

<hardware>
 <name>osiris</name>
 <chip type="fpga">
  <name>Xilinx_Virtex-II_6000</name>
  <area_max_usage>.9</area_max_usage>
  <area_min_usage>.2</area_min_usage>
  <area>33792</area>

  <resource type="blockram">
   <count>144</count>
   <size>18432</size>
  </resource>
 
  <resource type="multiplier">
    <count>144</count>
    <dimension1>18</dimension1>
    <dimension2>18</dimension2>
  </resource>

 </chip>

 <!-- ZBT SRAM --> 
 <chip type="ram">
  <count>10</count>
  <name>zbt_sram</name>
  <word_size>32</word_size>
  <size>4288</size>  <!-- supposed to be 524288 -->

  <port type="address_rw">
   <count> 1 </count>
   <clock>1</clock>
  </port>

  <port type="data_read">
   <count>1</count>
   <size>32</size>
   <read_latency>5</read_latency>
   <clock>1</clock>
  </port>

  <port type="data_write">
   <count>1</count>
   <size>32</size>
   <write_latency>1</write_latency>
   <clock>1</clock>
  </port>

 </chip>

 <!-- SDRAM --> 
 <chip type="ram">
  <count>1</count>
  <name>sdram</name>
  <word_size>64</word_size>
  <size>67108864</size>

  <port type="address_rw">
   <count> 1 </count>
   <clock>1</clock>
  </port>
  
  <port type="data_read">
   <count>1</count>
   <size>64</size>
   <read_latency>5</read_latency>
   <clock>1</clock>
  </port>

  <port type="data_write">
   <count>1</count>
   <size>64</size>
   <write_latency>1</write_latency>
   <clock>1</clock>
  </port>

 </chip>

</hardware>
